version: '2'
services: 
  web:
    image: hitalos/laravel:latest
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/
    command: php -S 0.0.0.0:80 -t public  
    environment:
        DB_HOST: db
        DB_DATABASE: ausbildungsnachweis
        DB_USERNAME: ausbildungsnachweis
        DB_PASSWORD: rootpass
        DB_CONNECTION: mysql
    links: 
      - db:db
  db:
    image: mariadb:latest
    ports: 
      - 3308:3306
    environment:
        MYSQL_ROOT_PASSWORD: rootpass
        MYSQL_DATABASE: ausbildungsnachweis
        MYSQL_USER: ausbildungsnachweis
        MYSQL_PASSWORD: rootpass

     
