version: '2'
services: 
  web:
    image: hitalos/laravel:latest
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/
    command: php -S 0.0.0.0:80 -t public public/index.php
    links:
        - db
    environment:
        DB_HOST: 172.19.0.2
        DB_USERNAME: root
        DB_PASSWORD: rootpass
        DB_CONNECTION: mysql
  db:
    image: mariadb:latest
    ports: 
      - 3308:3306
    environment:
        MYSQL_ROOT_PASSWORD: rootpass 
        MYSQL_DATABASE: ausbildungsnachweis
        MYSQL_USER: root
        MYSQL_PASSWORD: rootpass

