version: '2'
services: 
  web:
    image: hitalos/laravel:latest
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/
    command: php -S 0.0.0.0:80 -t public  
    links:
      - db:db
  db:
    image: fedora/postgresql:latest
    volumes:
      - ./db:/var/lib/pgsql/data/pgdata
    environment:
      - POSTGRES_DATABASE=ausbildungsnachweis
      - POSTGRES_USER=ausbildungsnachweis
      - POSTGRES_PASSWORD=ausbildungsnachweis
      - POSTGRESQL_CONTAINER_OPTS=assert_external_data = false ; clear_pgdata_pidfile = true

     
